import pygame
import random
from episode import *

pygame.init()
CLOCK = pygame.time.Clock()
FPS = 60
DEBUG = True
FONT = pygame.font.Font("beastboss_font.ttf", 90)
pygame.display.set_caption("Doctordle")

LOGO = pygame.image.load("logo.png")

SERIES_NAMES = {
    1: "Series One",
    2: "Series Two",
    3: "Series Three",
    4: "Series Four",
    5: "Series Five",
    6: "Series Six",
    7: "Series Seven",
    8: "Series Eight",
    9: "Series Nine",
    10: "Series Ten",
    11: "Series Eleven",
    12: "Series Twelve",
    13: "Series Thirteen",
    14: "60th",
    15: "Season One",
    16: "Season Two"
}

EPISODE_LIST = [Episode("S01x01", "Rose", 1, "9th Doctor", "RTD1", "Russell T Davies", "Keith Boak", 8),
                Episode("S01x02", "The End of the World", 1, "9th Doctor", "RTD1", "Russell T Davies", "Euros Lyn", 8.25),
                Episode("S01x03", "The Unquiet Dead", 1, "9th Doctor", "RTD1", "Mark Gatiss", "Keith Boak", 7.5),
                Episode("S01x04", "Aliens of London", 1, "9th Doctor", "RTD1", "Russell T Davies", "Keith Boak", 7),
                Episode("S01x05", "World War Three", 1, "9th Doctor", "RTD1", "Russell T Davies", "Keith Boak", 8),
                Episode("S01x06", "Dalek", 1, "9th Doctor", "RTD1", "Robert Shearman", "Joe Ahearne", 8.5),
                Episode("S01x07", "The Long Game", 1, "9th Doctor", "RTD1", "Russell T Davies", "Brian Grant", 6.5),
                Episode("S01x08", "Father's Day", 1, "9th Doctor", "RTD1", "Paul Cornell", "Joe Ahearne", 10),
                Episode("S01x09", "The Empty Child", 1, "9th Doctor", "RTD1", "Steven Moffat", "James Hawes", 7.5),
                Episode("S01x10", "The Doctor Dances", 1, "9th Doctor", "RTD1", "Steven Moffat", "James Hawes", 9),
                Episode("S01x11", "Boom Town", 1, "9th Doctor", "RTD1", "Russell T Davies", "Joe Ahearne", 7.5),
                Episode("S01x12", "Bad Wolf", 1, "9th Doctor", "RTD1", "Russell T Davies", "Joe Ahearne", 9),
                Episode("S01x13", "The Parting of the Ways", 1, "9th Doctor", "RTD1", "Russell T Davies", "Joe Ahearne", 10),
                Episode("S02x00", "The Christmas Invasion", 2, "10th Doctor", "RTD1", "Russell T Davies", "James Hawes", 8),
                Episode("S02x01", "New Earth", 2, "10th Doctor", "RTD1", "Russell T Davies", "James Hawes", 7.5),
                Episode("S02x02", "Tooth and Claw", 2, "10th Doctor", "RTD1", "Russell T Davies", "Euros Lyn", 7.5),
                Episode("S02x03", "School Reunion", 2, "10th Doctor", "RTD1", "Toby Whithouse", "James Hawes", 8),
                Episode("S02x04", "The Girl in the Fireplace", 2, "10th Doctor", "RTD1", "Steven Moffat", "Euros Lyn", 10),
                Episode("S02x05", "Rise of the Cybermen", 2, "10th Doctor", "RTD1", "Tom McRae", "Graeme Harper", 7.75),
                Episode("S02x06", "The Age of Steel", 2, "10th Doctor", "RTD1", "Tom McRae", "Graeme Harper", 7.75),
                Episode("S02x07", "The Idiot's Lantern", 2, "10th Doctor", "RTD1", "Mark Gatiss", "Euros Lyn", 7),
                Episode("S02x08", "The Impossible Planet", 2, "10th Doctor", "RTD1", "Matt Jones", "James Strong", 6.5),
                Episode("S02x09", "The Satan Pit", 2, "10th Doctor", "RTD1", "Matt Jones", "James Strong", 6.25),
                Episode("S02x10", "Love and Monsters", 2, "10th Doctor", "RTD1", "Russell T Davies", "Dan Zeff", 5.75),
                Episode("S02x11", "Fear Her", 2, "10th Doctor", "RTD1", "Matthew Graham", "Euros Lyn", 6.75),
                Episode("S02x12", "Army of Ghosts", 2, "10th Doctor", "RTD1", "Russell T Davies", "Graeme Harper", 8.5),
                Episode("S02x13", "Doomsday", 2, "10th Doctor", "RTD1", "Russell T Davies", "Graeme Harper", 9),
                Episode("S03x00", "The Runaway Bride", 3, "10th Doctor", "RTD1", "Russell T Davies", "Euros Lyn", 9.25),
                Episode("S03x01", "Smith & Jones", 3, "10th Doctor", "RTD1", "Russell T Davies", "Charles Palmer", 8.5),
                Episode("S03x02", "The Shakespeare Code", 3, "10th Doctor", "RTD1", "Gareth Roberts", "Charles Palmer", 8),
                Episode("S03x03", "Gridlock", 3, "10th Doctor", "RTD1", "Russell T Davies", "Richard Clark", 7.25),
                Episode("S03x04", "Daleks in Manhattan", 3, "10th Doctor", "RTD1", "Helen Raynor", "James Strong", 5.5),
                Episode("S03x05", "Evolution of the Daleks", 3, "10th Doctor", "RTD1", "Helen Raynor", "James Strong", 5),
                Episode("S03x06", "The Lazarus Experiment", 3, "10th Doctor", "RTD1", "Stephen Greenhorn", "Richard Clark", 7.75),
                Episode("S03x07", "42", 3, "10th Doctor", "RTD1", "Chris Chibnall", "Graeme Harper", 9.75),
                Episode("S03x08", "Human Nature", 3, "10th Doctor", "RTD1", "Paul Cornell", "Charles Palmer", 10),
                Episode("S03x09", "The Family of Blood", 3, "10th Doctor", "RTD1", "Paul Cornell", "Charles Palmer", 10),
                Episode("S03x10", "Blink", 3, "10th Doctor", "RTD1", "Steven Moffat", "Hettie MacDonald", 10),
                Episode("S03x11", "Utopia", 3, "10th Doctor", "RTD1", "Russell T Davies", "Graeme Harper", 9.25),
                Episode("S03x12", "The Sound of Drums", 3, "10th Doctor", "RTD1", "Russell T Davies", "Colin Teague", 8.5),
                Episode("S03x13", "The Last of the Time Lords", 3, "10th Doctor", "RTD1", "Russell T Davies", "Colin Teague", 7.5),
                Episode("S04x00", "Voyage of the Damned", 4, "10th Doctor", "RTD1", "Russell T Davies", "James Strong", 9.75),
                Episode("S04x01", "Partners in Crime", 4, "10th Doctor", "RTD1", "Russell T Davies", "James Strong", 9),
                Episode("S04x02", "The Fires of Pompeii", 4, "10th Doctor", "RTD1", "James Moran", "Colin Teague", 8.75),
                Episode("S04x03", "Planet of the Ood", 4, "10th Doctor", "RTD1", "Keith Temple", "Graeme Harper", 7.5),
                Episode("S04x04", "The Sontaran Stratagem", 4, "10th Doctor", "RTD1", "Helen Raynor", "Douglas MacKinnon", 8.5),
                Episode("S04x05", "The Poison Sky", 4, "10th Doctor", "RTD1", "Helen Raynor", "Douglas MacKinnon", 8.5),
                Episode("S04x06", "The Doctor's Daughter", 4, "10th Doctor", "RTD1", "Stephen Greenhorn", "Alice Troughton", 7),
                Episode("S04x07", "The Unicorn and the Wasp", 4, "10th Doctor", "RTD1", "Gareth Roberts", "Graeme Harper", 10),
                Episode("S04x08", "Silence in the Library", 4, "10th Doctor", "RTD1", "Steven Moffat", "Euros Lyn", 10),
                Episode("S04x09", "Forest of the Dead", 4, "10th Doctor", "RTD1", "Steven Moffat", "Euros Lyn", 10),
                Episode("S04x10", "Midnight", 4, "10th Doctor", "RTD1", "Russell T Davies", "Alice Troughton", 10),
                Episode("S04x11", "Turn Left", 4, "10th Doctor", "RTD1", "Russell T Davies", "Graeme Harper", 10),
                Episode("S04x12", "The Stolen Earth", 4, "10th Doctor", "RTD1", "Russell T Davies", "Graeme Harper", 9),
                Episode("S04x13", "Journey's End", 4, "10th Doctor", "RTD1", "Russell T Davies", "Graeme Harper", 10),
                Episode("S04x14", "The Next Doctor", 4, "10th Doctor", "RTD1", "Russell T Davies", "Andy Goddard", 8),
                Episode("S04x15", "Planet of the Dead", 4, "10th Doctor", "RTD1", "Gareth Roberts", "James Strong", 8.5),
                Episode("S04x16", "The Waters of Mars", 4, "10th Doctor", "RTD1", "Phil Ford", "Graeme Harper", 10),
                Episode("S04x17", "The End of Time Part One", 4, "10th Doctor", "RTD1", "Russell T Davies", "Euros Lyn", 9),
                Episode("S04x18", "The End of Time Part Two", 4, "10th Doctor", "RTD1", "Russell T Davies", "Euros Lyn", 10),
                Episode("S05x01", "The Eleventh Hour", 5, "11th Doctor", "The Grand Moff", "Steven Moffat", "Adam Smith", 10),
                Episode("S05x02", "The Beast Below", 5, "11th Doctor", "The Grand Moff", "Steven Moffat", "Andrew Gunn", 8),
                Episode("S05x03", "Victory of the Daleks", 5, "11th Doctor", "The Grand Moff", "Mark Gatiss", "Andrew Gunn", 7.75),
                Episode("S05x04", "The Time of Angels", 5, "11th Doctor", "The Grand Moff", "Steven Moffat", "Adam Smith", 7),
                Episode("S05x05", "Flesh and Stone", 5, "11th Doctor", "The Grand Moff", "Steven Moffat", "Adam Smith", 6),
                Episode("S05x06", "The Vampires of Venice", 5, "11th Doctor", "The Grand Moff", "Toby Whithouse", "Jonny Campbell", 8),
                Episode("S05x07", "Amy's Choice", 5, "11th Doctor", "The Grand Moff", "Simon Nye", "Catherine Morshead", 10),
                Episode("S05x08", "The Hungry Earth", 5, "11th Doctor", "The Grand Moff", "Chris Chibnall", "Ashley Way", 6.5),
                Episode("S05x09", "Cold Blood", 5, "11th Doctor", "The Grand Moff", "Chris Chibnall", "Ashley Way", 7),
                Episode("S05x10", "Vincent and the Doctor", 5, "11th Doctor", "The Grand Moff", "Richard Curtis", "Jonny Campbell", 10),
                Episode("S05x11", "The Lodger", 5, "11th Doctor", "The Grand Moff", "Gareth Roberts", "Catherine Morshead", 7.5),
                Episode("S05x12", "The Pandorica Opens", 5, "11th Doctor", "The Grand Moff", "Steven Moffat", "Toby Haynes", 8),
                Episode("S05x13", "The Big Bang", 5, "11th Doctor", "The Grand Moff", "Steven Moffat", "Toby Haynes", 9.5),
                Episode("S05x14", "A Christmas Carol", 5, "11th Doctor", "The Grand Moff", "Steven Moffat", "Toby Haynes", 10),
                Episode("S06x01", "The Impossible Astronaut", 6, "11th Doctor", "The Grand Moff", "Steven Moffat", "Toby Haynes", 8),
                Episode("S06x02", "Day of the Moon", 6, "11th Doctor", "The Grand Moff", "Steven Moffat", "Toby Haynes", 8.5),
                Episode("S06x03", "The Curse of the Black Spot", 6, "11th Doctor", "The Grand Moff", "Steve Thompson", "Jeremy Webb", 8),
                Episode("S06x04", "The Doctor's Wife", 6, "11th Doctor", "The Grand Moff", "Neil Gaiman", "Richard Clark", 10),
                Episode("S06x05", "The Rebel Flesh", 6, "11th Doctor", "The Grand Moff", "Matthew Graham", "Julian Simpson", 8.75),
                Episode("S06x06", "The Almost People", 6, "11th Doctor", "The Grand Moff", "Matthew Graham", "Julian Simpson", 9),
                Episode("S06x07", "A Good Man Goes to War", 6, "11th Doctor", "The Grand Moff", "Steven Moffat", "Peter Hoar", 9),
                Episode("S06x08", "Let's Kill Hitler", 6, "11th Doctor", "The Grand Moff", "Steven Moffat", "Richard Senior", 7.5),
                Episode("S06x09", "Night Terrors", 6, "11th Doctor", "The Grand Moff", "Mark Gatiss", "Richard Clark", 6.5),
                Episode("S06x10", "The Girl Who Waited", 6, "11th Doctor", "The Grand Moff", "Tom McRae", "Nick Hurran", 8.75),
                Episode("S06x11", "The God Complex", 6, "11th Doctor", "The Grand Moff", "Toby Whithouse", "Nick Hurran", 10),
                Episode("S06x12", "Closing Time", 6, "11th Doctor", "The Grand Moff", "Gareth Roberts", "Steve Hughes", 6),
                Episode("S06x13", "The Wedding of River Song", 6, "11th Doctor", "The Grand Moff", "Steven Moffat", "Jeremy Webb", 6.5),
                Episode("S06x14", "The Doctor, the Widow, and the Wardrobe", 6, "11th Doctor", "The Grand Moff", "Steven Moffat", "Farren Blackburn", 6),
                Episode("S07x01", "Asylum of the Daleks", 7, "11th Doctor", "The Grand Moff", "Steven Moffat", "Nick Hurran", 7),
                Episode("S07x02", "Dinosaurs on a Spaceship", 7, "11th Doctor", "The Grand Moff", "Chris Chibnall", "Saul Metzstein", 7.5),
                Episode("S07x03", "A Town Called Mercy", 7, "11th Doctor", "The Grand Moff", "Toby Whithouse", "Saul Metzstein", 8.25),
                Episode("S07x04", "The Power of Three", 7, "11th Doctor", "The Grand Moff", "Chris Chibnall", "Douglas MacKinnon", 7.75),
                Episode("S07x05", "The Angels Take Manhattan", 7, "11th Doctor", "The Grand Moff", "Steven Moffat", "Nick Hurran", 8.5),
                Episode("S07xmas", "The Snowmen", 7, "11th Doctor", "The Grand Moff", "Steven Moffat", "Saul Metzstein", 9),
                Episode("S07x06", "The Bells of Saint John", 7, "11th Doctor", "The Grand Moff", "Steven Moffat", "Colm McCarthy", 8.75),
                Episode("S07x07", "The Rings of Akhaten", 7, "11th Doctor", "The Grand Moff", "Neil Cross", "Farren Blackburn", 6.75),
                Episode("S07x08", "Cold War", 7, "11th Doctor", "The Grand Moff", "Mark Gatiss", "Douglas MacKinnon", 8.25),
                Episode("S07x09", "Hide", 7, "11th Doctor", "The Grand Moff", "Neil Cross", "Jamie Payne", 8.5),
                Episode("S07x10", "Journey to the Centre of the TARDIS", 7, "11th Doctor", "The Grand Moff", "Steve Thompson", "Mat King", 7),
                Episode("S07x11", "The Crimson Horror", 7, "11th Doctor", "The Grand Moff", "Mark Gatiss", "Saul Metzstein", 9),
                Episode("S07x12", "Nightmare in Silver", 7, "11th Doctor", "The Grand Moff", "Neil Gaiman", "Stephen Woolfenden", 8.75),
                Episode("S07x13", "The Name of the Doctor", 7, "11th Doctor", "The Grand Moff", "Steven Moffat", "Saul Metzstein", 7.25),
                Episode("S07x14", "The Day of the Doctor", 7, "11th Doctor", "The Grand Moff", "Steven Moffat", "Nick Hurran", 10),
                Episode("S07x15", "The Time of the Doctor", 7, "11th Doctor", "The Grand Moff", "Steven Moffat", "Jamie Payne", 10),
                Episode("S08x01", "Deep Breath", 8, "12th Doctor", "The Grand Moff", "Steven Moffat", "Ben Wheatley", 9),
                Episode("S08x02", "Into the Dalek", 8, "12th Doctor", "The Grand Moff", "Phil Ford", "Ben Wheatley", 8),
                Episode("S08x03", "Robot of Sherwood", 8, "12th Doctor", "The Grand Moff", "Mark Gatiss", "Paul Murphy", 9.25),
                Episode("S08x04", "Listen", 8, "12th Doctor", "The Grand Moff", "Steven Moffat", "Douglas MacKinnon", 8),
                Episode("S08x05", "Time Heist", 8, "12th Doctor", "The Grand Moff", "Steve Thompson", "Douglas MacKinnon", 9.75),
                Episode("S08x06", "The Caretaker", 8, "12th Doctor", "The Grand Moff", "Gareth Roberts", "Paul Murphy", 7.5),
                Episode("S08x07", "Kill the Moon", 8, "12th Doctor", "The Grand Moff", "Peter Harness", "Paul Wilmhurst", 6),
                Episode("S08x08", "Mummy on the Orient Express", 8, "12th Doctor", "The Grand Moff", "Jamie Mathieson", "Paul Wilmhurst", 10),
                Episode("S08x09", "Flatline", 8, "12th Doctor", "The Grand Moff", "Jamie Mathieson", "Douglas MacKinnon", 10),
                Episode("S08x10", "In the Forest of the Night", 8, "12th Doctor", "The Grand Moff", "Frank Cottrell-Boyce", "Sheree Folkson", 4),
                Episode("S08x11", "Dark Water", 8, "12th Doctor", "The Grand Moff", "Steven Moffat", "Rachel Talalay", 10),
                Episode("S08x12", "Death in Heaven", 8, "12th Doctor", "The Grand Moff", "Steven Moffat", "Rachel Talalay", 9.25),
                Episode("S08x13", "Last Christmas", 8, "12th Doctor", "The Grand Moff", "Steven Moffat", "Paul Wilmhurst", 8.75),
                Episode("S09x01", "The Magician's Apprentice", 9, "12th Doctor", "The Grand Moff", "Steven Moffat", "Hettie MacDonald", 7.5),
                Episode("S09x02", "The Witch's Familiar", 9, "12th Doctor", "The Grand Moff", "Steven Moffat", "Hettie MacDonald", 8),
                Episode("S09x03", "Under the Lake", 9, "12th Doctor", "The Grand Moff", "Toby Whithouse", "Daniel O'Hara", 10),
                Episode("S09x04", "Before the Flood", 9, "12th Doctor", "The Grand Moff", "Toby Whithouse", "Daniel O'Hara", 10),
                Episode("S09x05", "The Girl Who Died", 9, "12th Doctor", "The Grand Moff", "Jamie Mathieson", "Ed Bazalgette", 7.5),
                Episode("S09x06", "The Woman Who Lived", 9, "12th Doctor", "The Grand Moff", "Catherine Tregenna", "Ed Bazalgette", 7.25),
                Episode("S09x07", "The Zygon Invasion", 9, "12th Doctor", "The Grand Moff", "Peter Harness", "Daniel Nettheim", 7),
                Episode("S09x08", "The Zygon Inversion", 9, "12th Doctor", "The Grand Moff", "Peter Harness", "Daniel Nettheim", 9),
                Episode("S09x09", "Sleep No More", 9, "12th Doctor", "The Grand Moff", "Mark Gatiss", "Justin Molotnikov", 8),
                Episode("S09x10", "Face the Raven", 9, "12th Doctor", "The Grand Moff", "Sarah Dollard", "Justin Molotnikov", 8.5),
                Episode("S09x11", "Heaven Sent", 9, "12th Doctor", "The Grand Moff", "Steven Moffat", "Rachel Talalay", 10),
                Episode("S09x12", "Hell Bent", 9, "12th Doctor", "The Grand Moff", "Steven Moffat", "Rachel Talalay", 9.75),
                Episode("S09x13", "The Husbands of River Song", 9, "12th Doctor", "The Grand Moff", "Steven Moffat", "Douglas MacKinnon", 10),
                Episode("S10x00", "The Return of Doctor Mysterio", 10, "12th Doctor", "The Grand Moff", "Steven Moffat", "Ed Bazalgette", 9),
                Episode("S10x01", "The Pilot", 10, "12th Doctor", "The Grand Moff", "Steven Moffat", "Laurence Gough", 9),
                Episode("S10x02", "Smile", 10, "12th Doctor", "The Grand Moff", "Frank Cottrell-Boyce", "Laurence Gough", 8),
                Episode("S10x03", "Thin Ice", 10, "12th Doctor", "The Grand Moff", "Sarah Dollard", "Bill Anderson", 8),
                Episode("S10x04", "Knock Knock", 10, "12th Doctor", "The Grand Moff", "Mike Bartlett", "Bill Anderson", 9),
                Episode("S10x05", "Oxygen", 10, "12th Doctor", "The Grand Moff", "Jamie Mathieson", "Charles Palmer", 9.5),
                Episode("S10x06", "Extremis", 10, "12th Doctor", "The Grand Moff", "Steven Moffat", "Daniel Nettheim", 10),
                Episode("S10x07", "The Pyramid and the End of the World", 10, "12th Doctor", "The Grand Moff", "Peter Harness", "Daniel Nettheim", 9.75),
                Episode("S10x08", "The Lie of the Land", 10, "12th Doctor", "The Grand Moff", "Toby Whithouse", "Wayne Yip", 9),
                Episode("S10x09", "Empress of Mars", 10, "12th Doctor", "The Grand Moff", "Mark Gatiss", "Wayne Yip", 7),
                Episode("S10x10", "The Eaters of Light", 10, "12th Doctor", "The Grand Moff", "Rona Munro", "Charles Palmer", 6.5),
                Episode("S10x11", "World Enough and Time", 10, "12th Doctor", "The Grand Moff", "Steven Moffat", "Rachel Talalay", 10),
                Episode("S10x12", "The Doctor Falls", 10, "12th Doctor", "The Grand Moff", "Steven Moffat", "Rachel Talalay", 10),
                Episode("S10x13", "Twice Upon a Time", 10, "12th Doctor", "The Grand Moff", "Steven Moffat", "Rachel Talalay", 9.75),
                Episode("S11x01", "The Woman Who Fell to Earth", 11, "13th Doctor", "Chibbers", "Chris Chibnall", "Jamie Childs", 9),
                Episode("S11x02", "The Ghost Monument", 11, "13th Doctor", "Chibbers", "Chris Chibnall", "Mark Tonderai", 7),
                Episode("S11x03", "Rosa", 11, "13th Doctor", "Chibbers", "Malorie Blackman", "Mark Tonderai", 9),
                Episode("S11x04", "Arachnids in the UK", 11, "13th Doctor", "Chibbers", "Chris Chibnall", "Sallie Aprahamian", 6),
                Episode("S11x05", "The Tsuranga Conundrum", 11, "13th Doctor", "Chibbers", "Chris Chibnall", "Jennifer Perrott", 7),
                Episode("S11x06", "Demons of the Punjab", 11, "13th Doctor", "Chibbers", "Vinay Patel", "Jamie Childs", 9),
                Episode("S11x07", "Kerblam!", 11, "13th Doctor", "Chibbers", "Pete McTighe", "Jennifer Perrott", 9),
                Episode("S11x08", "The Witchfinders", 11, "13th Doctor", "Chibbers", "Joy Wilkinson", "Sallie Aprahamian", 9),
                Episode("S11x09", "It Takes You Away", 11, "13th Doctor", "Chibbers", "Ed Hime", "Jamie Childs", 9.5),
                Episode("S11x10", "The Battle of Ranskoor av Kolos", 11, "13th Doctor", "Chibbers", "Chris Chibnall", "Jamie Childs", 3),
                Episode("S11x11", "Resolution", 11, "13th Doctor", "Chibbers", "Chris Chibnall", "Wayne Yip", 10),
                Episode("S12x01", "Spyfall, Part One", 12, "13th Doctor", "Chibbers", "Chris Chibnall", "Jamie Magnus Stone", 9.25),
                Episode("S12x02", "Spyfall, Part Two", 12, "13th Doctor", "Chibbers", "Chris Chibnall", "Lee Haven Jones", 8.5),
                Episode("S12x03", "Orphan 55", 12, "13th Doctor", "Chibbers", "Ed Hime", "Lee Haven Jones", 1),
                Episode("S12x04", "Nikola Tesla's Night of Terror", 12, "13th Doctor", "Chibbers", "Nina Metivier", "Nida Manzoor", 8.5),
                Episode("S12x05", "Fugitive of the Judoon", 12, "13th Doctor", "Chibbers", "Vinay Patel", "Nida Manzoor", 8.75),
                Episode("S12x06", "Praxeus", 12, "13th Doctor", "Chibbers", "Pete McTighe", "Jamie Magnus Stone", 7),
                Episode("S12x07", "Can You Hear Me?", 12, "13th Doctor", "Chibbers", "Charlene James", "Emma Sullivan", 9),
                Episode("S12x08", "The Haunting of Villa Diodati", 12, "13th Doctor", "Chibbers", "Maxine Alderton", "Emma Sullivan", 10),
                Episode("S12x09", "Ascension of the Cybermen", 12, "13th Doctor", "Chibbers", "Chris Chibnall", "Jamie Magnus Stone", 7.5),
                Episode("S12x10", "The Timeless Children", 12, "13th Doctor", "Chibbers", "Chris Chibnall", "Jamie Magnus Stone", 9),
                Episode("S12x11", "Revolution of the Daleks", 12, "13th Doctor", "Chibbers", "Chris Chibnall", "Lee Haven Jones", 9),
                Episode("S13x01", "The Halloween Apocalypse", 13, "13th Doctor", "Chibbers", "Chris Chibnall", "Jamie Magnus Stone", 7.75),
                Episode("S13x02", "War of the Sontarans", 13, "13th Doctor", "Chibbers", "Chris Chibnall", "Jamie Magnus Stone", 6.75),
                Episode("S13x03", "Once, Upon Time", 13, "13th Doctor", "Chibbers", "Chris Chibnall", "Azhur Saleem", 6.5),
                Episode("S13x04", "Village of the Angels", 13, "13th Doctor", "Chibbers", "Maxine Alderton", "Jamie Magnus Stone", 8),
                Episode("S13x05", "Survivors of the Flux", 13, "13th Doctor", "Chibbers", "Chris Chibnall", "Azhur Saleem", 8),
                Episode("S13x06", "The Vanquishers", 13, "13th Doctor", "Chibbers", "Chris Chibnall", "Azhur Saleem", 8),
                Episode("S13x07", "Eve of the Daleks", 13, "13th Doctor", "Chibbers", "Chris Chibnall", "Annetta Laufer", 10),
                Episode("S13x08", "Legend of the Sea Devils", 13, "13th Doctor", "Chibbers", "Ella Road", "Haolu Wang", 3),
                Episode("S13x09", "The Power of the Doctor", 13, "13th Doctor", "Chibbers", "Chris Chibnall", "Jamie Magnus Stone", 10),
                Episode("60thx01", "The Star Beast", 14, "14th Doctor", "RTD2", "Russell T Davies", "Rachel Talalay", 8),
                Episode("60thx02", "Wild Blue Yonder", 14, "14th Doctor", "RTD2", "Russell T Davies", "Tom Kingsley", 10),
                Episode("60thx03", "The Giggle", 14, "14th Doctor", "RTD2", "Russell T Davies", "Chanya Button", 10),
                Episode("S14x00", "The Church on Ruby Road", 15, "15th Doctor", "RTD2", "Russell T Davies", "Mark Tonderai", 8.75),
                Episode("S14x01", "Space Babies", 15, "15th Doctor", "RTD2", "Russell T Davies", "Julie Anne Robinson", 7),
                Episode("S14x02", "The Devil's Chord", 15, "15th Doctor", "RTD2", "Russell T Davies", "Ben Chessell", 10),
                Episode("S14x03", "Boom", 15, "15th Doctor", "RTD2", "Steven Moffat", "Julie Anne Robinson", 10),
                Episode("S14x04", "73 Yards", 15, "15th Doctor", "RTD2", "Russell T Davies", "Dylan Holmes Williams", 8.5),
                Episode("S14x05", "Dot and Bubble", 15, "15th Doctor", "RTD2", "Russell T Davies", "Dylan Holmes Williams", 9.5),
                Episode("S14x06", "Rogue", 15, "15th Doctor", "RTD2", "Kate Herron and Briony Redman", "Ben Chessell", 10),
                Episode("S14x07", "The Legend of Ruby Sunday", 15, "15th Doctor", "RTD2", "Russell T Davies", "Jamie Donoughue", 9.25),
                Episode("S14x08", "Empire of Death", 15, "15th Doctor", "RTD2", "Russell T Davies", "Jamie Donoughue", 7.75),
                Episode("S15x00", "Joy to the World", 16, "15th Doctor", "RTD2", "Steven Moffat", "Alex Pillai", 8.75),
                Episode("S15x01", "The Robot Revolution", 16, "15th Doctor", "RTD2", "Russell T Davies", "Peter Hoar", 8.5),
                Episode("S15x02", "Lux", 16, "15th Doctor", "RTD2", "Russell T Davies", "Amanda Brotchie", 10),
                Episode("S15x03", "The Well", 16, "15th Doctor", "RTD2", "Sharma Angel-Walfall", "Amanda Brotchie", 10),
                Episode("S15x04", "Lucky Day", 16, "15th Doctor", "RTD2", "Pete McTighe", "Peter Hoar", 9.25),
                Episode("S15x05", "The Story & The Engine", 16, "15th Doctor", "RTD2", "Inua Ellams", "Makalla McPherson", 8.75),
                Episode("S15x06", "The Interstellar Song Contest", 16, "15th Doctor", "RTD2", "Juno Dawson", "Ben Williams", 9.75),
                Episode("S15x07", "Wish World", 16, "15th Doctor", "RTD2", "Russell T Davies", "Alex Pillai", 9.5),
                Episode("S15x08", "The Reality War", 16, "15th Doctor", "RTD2", "Russell T Davies", "Alex Pillai", 10)]
CORRECT_EPISODE = EPISODE_LIST[random.randint(0, len(EPISODE_LIST) - 1)]
ALLOWED_KEYS = [pygame.K_0, pygame.K_1, pygame.K_2, pygame.K_3, pygame.K_4, pygame.K_5, pygame.K_6, pygame.K_7, pygame.K_8, pygame.K_9, pygame.K_a, pygame.K_b,
                pygame.K_c, pygame.K_d, pygame.K_e, pygame.K_f, pygame.K_g, pygame.K_h, pygame.K_i, pygame.K_j, pygame.K_k, pygame.K_l, pygame.K_m, pygame.K_n,
                pygame.K_o, pygame.K_p, pygame.K_q, pygame.K_r, pygame.K_s, pygame.K_t, pygame.K_u, pygame.K_v, pygame.K_w, pygame.K_x, pygame.K_y, pygame.K_z,
                pygame.K_BACKSPACE, pygame.K_COMMA, pygame.K_QUESTION, pygame.K_SPACE, pygame.K_RETURN, pygame.K_QUOTE]

class Doctordle:
    guessed_episodes = []
    current_search = ""
    search_index = 0
    text_surfaces = []
    search_list = []
    width, height = 1280, 720
    screen = pygame.display.set_mode((width, height), pygame.RESIZABLE)